services:
  db:
    image: postgres:15
    container_name: harms_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=harms
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
    ports:
      - "5431:5431"
    networks:
      - harms_network

  redis:
    image: redis:7-alpine
    container_name: harms_redis
    ports:
      - "6379:6379"
    networks:
      - harms_network

  web:
    build: .
    container_name: harms_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - media_volume:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - harms_network

  celery:
    build: .
    container_name: harms_celery
    command: celery -A config worker -l info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - harms_network

volumes:
  postgres_data:
  media_volume:

networks:
  harms_network:
    driver: bridge